### ISSUE TITLE
Can you provide more details to compile the program?

### ISSUE THREAD

**Issue by caesar0301** [humnetlab/mobilityMotifs#1]
Hi there,
I want to re-estimate the mobifs from my data sets. But I can not compile the program according to the readme or source code comments. Could you please give more details about that?

Xiaming

**Comment by jamesonthecrow** [comment]
Hi Xiaming,

I am not the one who originally wrote this code (it was a former Post-doc who is no longer with the lab), but I think I fixed a few issues with example.cc.

You can compile using:

```
g++ example.cc -O3 -o example
```

Be sure you unrar the data_example.rar file first.

If you have anymore issues I can try to help, but like I said, I do not know this code well at all.

Best of luck.
